version: '3.8'

services:
  vault:
    image: hashicorp/vault-enterprise
    container_name: vault-enterprise
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_API_ADDR: "http://localhost:8200"
      VAULT_DISABLE_MLOCK: "true"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
      - ./vault-config:/vault/config
    ports:
      - "8200:8200"
    networks:
      - vault-network
    hostname: vault.local
    command: vault server -dev -dev-root-token-id="myroot" -dev-listen-address="0.0.0.0:8200"

volumes:
  vault_data:
  vault_logs:

networks:
  vault-network:
    driver: bridge
